### ISSUE TITLE
Add Strafemeter

### ISSUE THREAD

**Issue by phgpzev** [quartz55/reflexrun#2]
Add strafe meter to the hud = optimizing strafes

**Comment by quartz55** [comment]
- [X] Vector2D class
- [X] Accel meter
- [X] Get optimal angle
- [X] Get velocity angle
- [X] Get player angle
- [x] Find a better way to deal with relative angles
- [x] Adjust strafe angle according to player turning (left or right)
- [x] Optimize for reflex
- [x] Smooth display (it's too jerky atm)
- [x] testestestestestestest AND TEST
